i18n(fr): hot-corner translation added + typos
pop-os/desktop-widget pull request #93
Opened 2022-04-15 15:28 UTC by pog31

Hi
I 've improved french translation by fixing typos and adding new translation for hot-corner term

2022-04-15 15:59 UTC, mmstick approved these changes

2022-04-18 21:04 UTC, jackpot51 approved these changes

2022-04-19 23:10 UTC, n3m0-22 requested changes
Under Dock Options the translation for Icon Click Action "Action lorsque vous cliquez sur l'icône" is so long it is not fully displayed even with the window maximized. Can we get a more concise translation?
![Capture d’écran du 2022-04-19 15-50-09](https://user-images.githubusercontent.com/11048214/164115888-078ad613-b01d-4f92-bb1d-776de52ee8c0.png)

2022-04-20 07:11 UTC, pog31 commented
So  a more concise translation could be:
"Action en cliquant sur l'icône". 
I think the length will be ok this time.
Do i need to make a new commit?

2022-04-21 16:54 UTC, n3m0-22 approved these changes

2022-04-21 16:56 UTC, merged